// This file is automatically generated by auto_version.zsh,DO NOT EDIT!
#if !defined(AUTO_VERSION_H)
#define AUTO_VERSION_H
#define APPNAME "gw"
#define VER_AUTO 1
#define VERSION "0.0.1"
#define BUILDTIME "2022.02.19 17:05:01"
#define BUILDTIMESTAMP 16452615013
#define major 0
#define minor 2022
#define patch 0219
#define build 170501
#include <stdio.h>

void printVersion()
{
    printf("version:%s build:%s\n",VERSION,BUILDTIME);
}

#endif //AUTO_VERSION_H
