// This file is automatically generated by auto_version.zsh,DO NOT EDIT!
#if !defined(AUTO_VERSION_H)
#define AUTO_VERSION_H
#define APPNAME "gw"
#define VER_AUTO 1
#define VERSION "0.0.2"
#define BUILDTIME "2026.04.20 17:46:20"
#define BUILDTIMESTAMP 17766783803
#define major 0
#define minor 2026
#define patch 0420
#define build 174620
#include <stdio.h>

#define printVersion() do {   printf("version:%s build:%s\n",VERSION,BUILDTIME);}while(0);

#endif //AUTO_VERSION_H
