#!/bin/zsh

# CUR_PATH="$( cd "$( dirname "$0"  )" && pwd  )
CUR_PATH="$(pwd)"
DATE_STRING=`date "+20%y.%m.%d %k:%M:%S"`

TIMESTAMP="$(date '+%s%3')"
echo $TIMESTAM

PATH_VERION_JSON=${CUR_PATH}/output/version.json
PATH_VERSION_HEADER=${CUR_PATH}/applications/auto_version.h

if [ -z $1 ] && [ -z $2] && [ -z $3 ];then
    echo "please input APPNAME and version"
    exit
else
    app_name=$1
    version_string=$2
    app_comment=$3
fi

# temp="{\"version\":\"${version_string}\",\"buildtime_string\":\"${DATE_STRING}\", \"buildtime\":${TIMESTAMP}, \"content\":\"${app_comment}\",\"download\":false,\"update\":false}" 
temp=" \
{ \
    \"version\":\"${version_string}\", \
    \"buildtime_string\":\"${DATE_STRING}\", \
    \"buildtime\":${TIMESTAMP}, \
    \"content\":\"${app_comment}\", \
    \"download\":false,\
    \"update\":false\
} \
" 

new_json=$(cat ${PATH_VERION_JSON} | jq ".${app_name}=${temp}")

echo $new_json
echo $new_json >  ${PATH_VERION_JSON}

cFun_printVersion="
void printVersion()
{
    printf(\"version:%s build:%s\\n\",VERSION,BUILDTIME);
}
"


# -r 不对字符串进行转义
function write_line()
{
    print -r $1 >> ${PATH_VERSION_HEADER} 
}

function write_header_start()
{
    print "// This file is automatically generated by auto_version.zsh,DO NOT EDIT!" > ${PATH_VERSION_HEADER} 
    print "#if !defined(AUTO_VERSION_H)" >> ${PATH_VERSION_HEADER} 
    write_line "#define AUTO_VERSION_H"
    
}

function write_header_end()
{
    write_line "#endif //AUTO_VERSION_H"
}

major=0
minor=`date '+%Y'`
patch=`date '+%m%d'`
build=`date '+%H%M%S'`

write_header_start

write_line "#define APPNAME \"${app_name}\""
write_line "#define VER_AUTO 1"
write_line "#define VERSION \"${version_string}\""
write_line "#define BUILDTIME \"${DATE_STRING}\""	
write_line "#define BUILDTIMESTAMP ${TIMESTAMP}"
write_line "#define major ${major}"
write_line "#define minor ${minor}"
write_line "#define patch ${patch}"
write_line "#define build ${build}"

write_line "#include <stdio.h>"
write_line $cFun_printVersion

write_header_end

function gen_version(){
    local t=`date '+%Y.%m%d.%H%M%S'`  
    # echo $major.$t3  
    printf "%s" $major.$t
}

# if (($+1)) {
#     case $1 {
#         (app)
#             log_d "下载到 pack 到 SPI FLASH"
#              $NUWRITER $APP_INI
#         ;;
#         (*)
#             log_d "未知参数"
#         ;;
#     }
# } else {
#     log_d "开始编译"
#     scons -j 8
#     log_d "下载到 RAM"
#     $NUWRITER $RAM_INI
# }
