[RUN]
# Select mode, you are to select strages
# mode: SDRAM,SPINOR,SPINAND,SD, NAND #
mode= SPINAND

# "yes" if you want to burn all deivce #
# all_device: yes, no #
all_device = no


# "yes" if you want to pack image according to the mode #
# when pack is "yes", only multipe images are packaged into one file #
# pack: yes, no #
pack = no
pack_path = /Users/yangxiyuan/Projects/rtt-projects/rt-thread/bsp/nuvoton/gw/rtthread_pack.bin

[DDR]
# Select NUC980 series to initial SDRAM
# NUC980DF61YC.ini #
# NUC980DK61Y.ini  #
# NUC980DK61YC.ini #
# NUC980DR61Y.ini  #

ddr = NUC980DK61YC.ini

[SPINAND]
# This mode set "run" to control SPINAND flash and specify the type of the image. 
# These types can be recognized by bootloader or Linux. 
# The image type is set loader, data, environment or pack.

# program : write a new image to SPINAND
# program_verify : write a new image to SPINAND and verify image
# read : read data from SPINAND to your's computer.
# erase : erase SPINAND.
# run: program, program_verify, read, erase, #
run = program_verify

#------------------- program -------------------#
# type: data, env, loader, pack #
image_num = 1
image0_path=  /Users/yangxiyuan/Projects/rtt-projects/rt-thread/bsp/nuvoton/gw/rtthread_pack.bin
image0_type = pack


# "yes" if you are using user defined to config SPINAND parameters
# using_user_defined: yes, no #
using_user_defined = no
page_size=2048
spare_area=64
quad_read_command = 0x6b
read_status_command = 0xff
write_status_command = 0xff
status_value = 0xff
dummy_bytes = 0x1
blockperflash=1024
pageperflash=64

#------------------- read -------------------#
read_path =  /Users/yangxiyuan/Projects/rtt-projects/tools/pattern/record_spinand.bin
read_start_blocks = 0
read_offset_blocks = 10

#------------------- erase ------------------#
# erase_all: yes, no(Will use start blocks and offset blocks) #
erase_all = yes
erase_start_blocks = 0
erase_offset_blocks = 10

