[RUN]
# Select mode, you are to select strages
# mode: SDRAM,SPINOR,SPINAND,SD, NAND #
mode= SDRAM


# "yes" if you want to burn all deivce #
 
# all_device: yes, no #
all_device = no


# "yes" if you want to pack image according to the mode #
# when pack is "yes", only multipe images are packaged into one file #
# pack: yes, no #
pack = no
pack_path = /Users/yangxiyuan/Projects/rtt-projects/rt-thread/bsp/nuvoton/gw/rtthread.bin

[DDR]
# Select NUC980 series to initial SDRAM
# NUC980DF61YC.ini #
# NUC980DK61Y.ini  #
# NUC980DK61YC.ini #
# NUC980DR61Y.ini  #

ddr = NUC980DK61YC.ini

[SDRAM]
# The SDRAM mode is used to download an image to
# DDR or SDRAM for debugging purpose. 

# Select “Download only” or ”Download and run”
# option: download, run #
option = run
sdram_path = /Users/yangxiyuan/Projects/rtt-projects/rt-thread/bsp/nuvoton/gw/rtthread.bin
exe_addr = 0x000


# "yes" if you are to burn dtb file.
# using_dtb: yes, no #
using_dtb = no
dtb_path = ./pattern/kernel/nuc980-dev-v1.0.dtb
dtb_addr = 0x1400000


